### ISSUE TITLE
Could not load type 'QRCoder.QRCode'

### ISSUE THREAD

**Issue by thanhnntq** [BrandonPotter/GoogleAuthenticator#100]
```
System.TypeLoadException: Could not load type 'QRCoder.QRCode' from assembly 'QRCoder, Version=1.4.3.0, Culture=neutral, PublicKeyToken=c4ed5b9ae8358a28'.
   at Google.Authenticator.TwoFactorAuthenticator.GenerateQrCodeUrl(Int32 qrPixelsPerModule, String provisionUrl)
   at Google.Authenticator.TwoFactorAuthenticator.GenerateSetupCode(String issuer, String accountTitleNoSpaces, Byte[] accountSecretKey, Int32 qrPixelsPerModule, Boolean generateQrCode)
   at Google.Authenticator.TwoFactorAuthenticator.GenerateSetupCode(String issuer, String accountTitleNoSpaces, String accountSecretKey, Boolean secretIsBase32, Int32 qrPixelsPerModule)
   at Security.Authentication.TwoFactorAuthenticatorProvider.GenerateSetupCode(String issuer, String title, String secretKey, String email)
```
```

private readonly TwoFactorAuthenticator _authenticator;

    public TwoFactorAuthenticatorProvider()
    {
        _authenticator = new TwoFactorAuthenticator();
    }
public SetupCode GenerateSetupCode(string issuer, string title, string secretKey)
    {
        var sc = _authenticator.GenerateSetupCode(issuer, title, secretKey, false, 3);
        return sc;
    }
```

![image](https://user-images.githubusercontent.com/30698814/160870684-8d99bb8d-c2ea-415b-a073-e1034833dfab.png)

**Comment by naviln** [comment]
Yeah I'm having this problem with .NET 6.
Downgrading/Staying on version 2.3.0 of this library worked for me

**Comment by FighterLuo** [comment]
I have the same problem, .NET 6
please fix it, thanks

**Comment by neosonne** [comment]
me too
