### ISSUE TITLE
Method not found for test build

### ISSUE THREAD

**Issue by lxman** [BrandonPotter/GoogleAuthenticator#68]
We've got something odd going on. We've got a moderately large solution - about 60 projects in the solution, using .NET 4.8. We have three targets set up for our build, Debug, Test and Release. With the latest version of your product (v2.2.0) only with our test build, we have suddenly started getting method not found for any of the methods we try to access. It works perfectly well when we compile for Debug. It's just when we compile for our Test release. We have had to drop back to the 2.1.1 release to resolve the issue for now.

**Comment by ahwm** [comment]
Unfortunately, I don't know if we've gotten enough information. But here goes based on what you have stated.

Version 2.2 did increment some dependency versions. One in particular that I could see potentially causing issues for you is the upgrade of `Microsoft.NET.Test.Sdk` from version 16.2 to version 16.10. I can't see that any other changes would have had that effect on your solution. What if you tried upgrading just this package in your project(s) and see if you get the same behavior with version 2.1.1?

**Comment by lxman** [comment]
We're still playing with it - I appreciate the info about the dll change. That might be useful. I'm currently digging into our build server to see if I find anything. I'll post back when I get any useful info.

**Comment by lxman** [comment]
Ok, we've set up fusion logging to take a look, and it appears that the dll binds successfully - the only thing of note is that we get a message about "No native image found," which I feel like might be a bit of a red herring in this case. The actual error we are receiving is this:

![image](https://user-images.githubusercontent.com/20031555/130643282-245c4981-c92d-4f87-badf-bebad3873c89.png)

The details:

************** Exception Text **************
System.MissingMethodException: Method not found: 'Boolean Google.Authenticator.TwoFactorAuthenticator.ValidateTwoFactorPIN(System.String, System.String)'.
   at DrakeAccounting.frmAdminSetup_Tab_Controls.GoogleAuthenticator.CheckValidator()
   at DrakeAccounting.frmAdminSetup_Tab_Controls.GoogleAuthenticator.<SetupValidator>b__12_0()
   at DrakeAccountingCommon.Validation.Rules.CustomRule.CheckImplementation()
   at DrakeAccountingCommon.Validation.RuleBase.CheckOnlyThisRule()
   at DrakeAccountingCommon.Validation.RuleBase.Check()
   at DrakeAccountingCommon.Validation.RuleBase.OnTriggerInvoked(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at DrakeAccounting.frmAdminSetup_Tab_Controls.GoogleAuthenticator.LoadQR(Tuple`2 multiAuth)
   at DrakeAccounting.frmUserSetup.populateSelectedUser()
   at DrakeAccounting.frmUserSetup.set_CurrentUser(Security value)
   at DrakeAccounting.frmUserSetup.cmdNewSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at DrakeAccounting.frmUserSetup.frmAdminSetup_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by lxman** [comment]
Okay, a bit more info. Our patching system wasn't catching the change in the dll because the file version doesn't change, only the product version. We have resolved that. With that, I can definitely say that if we use the 2.1.1 version we are ok - if we move to 2.2.0 it fails.

**Comment by flytzen** [comment]
Okay, so the method in question actually has the following signature: 
```
        public bool ValidateTwoFactorPIN(
            string accountSecretKey,
            string twoFactorCodeFromClient,
            bool secretIsBase32 = false)
```
That last optional parameter was indeed added recently and may have been in 2.2.0. That *should* be fine - as long as the calling code is recompiled. If the calling code for some reason has not recompiled against the new signature, it will fail like what you describe. In hindsight, we should not have added an optional param but instead added an extra overload.

Simplest answer is probably to add a third parameter `false` to your call-site and re-compile.
